import type { Category, Ring } from '../data';

export type CurrentRadarLogo = {
  id: string; symbol: string; name: string; category: Category; ring: Ring;
  x: number; y: number; relatedNames: string[];
};

// Original SVG symbols and related topics from the public Tech Radar, 06.10.2026.
// Placement is adapted to the Figma geometry; this is a static source snapshot.
export const currentRadarLogos: CurrentRadarLogo[] = [
  {
    "id": "react",
    "symbol": "react",
    "name": "React",
    "category": "Languages & Frameworks",
    "ring": "Adopt",
    "x": 358.36,
    "y": 310.52,
    "relatedNames": [
      "JavaScript",
      "Vue",
      "Svelte",
      "Preact",
      "Node.js",
      "Angular",
      "TypeScript",
      "Cypress",
      "Jest",
      "webpack",
      "Microfrontend",
      "Redux",
      "Apollo",
      "Storybook",
      "Next.js",
      "sitespeed.io"
    ]
  },
  {
    "id": "typescript",
    "symbol": "typescript",
    "name": "TypeScript",
    "category": "Languages & Frameworks",
    "ring": "Adopt",
    "x": 382.32,
    "y": 206.62,
    "relatedNames": [
      "React",
      "JavaScript",
      "Preact",
      "Node.js",
      "Angular",
      "Next.js",
      "Playwright",
      "Vitest",
      "sitespeed.io"
    ]
  },
  {
    "id": "figma",
    "symbol": "figma",
    "name": "Figma",
    "category": "Languages & Frameworks",
    "ring": "Adopt",
    "x": 427.94,
    "y": 290.42,
    "relatedNames": [
      "React",
      "TypeScript",
      "Microfrontend",
      "Sass",
      "Tailwind CSS",
      "Radix UI",
      "Panda CSS",
      "Storybook",
      "sitespeed.io",
      "StyleX"
    ]
  },
  {
    "id": "serverless",
    "symbol": "serverless",
    "name": "Serverless",
    "category": "Techniques",
    "ring": "Adopt",
    "x": 282.03,
    "y": 246.75,
    "relatedNames": [
      "AWS",
      "Azure",
      "DevOps",
      "Docker",
      "Terraform",
      "Serverless",
      "AWS Fargate",
      "AWS Amplify",
      "OpenTofu"
    ]
  },
  {
    "id": "cicd",
    "symbol": "cicd",
    "name": "CICD",
    "category": "Techniques",
    "ring": "Adopt",
    "x": 189.01,
    "y": 299.43,
    "relatedNames": [
      "Automated Security Testing",
      "Statische Codeanalyse",
      "GitLab",
      "DevOps",
      "Go",
      "SonarQube",
      "Terraform",
      "Kubernetes",
      "Puppet",
      "Docker",
      "Ansible",
      "DevSecOps",
      "AWS Amplify",
      "Trivy",
      "DependencyTrack",
      "OpenTofu"
    ]
  },
  {
    "id": "ddd",
    "symbol": "ddd",
    "name": "DDD",
    "category": "Techniques",
    "ring": "Adopt",
    "x": 204.2,
    "y": 255.63,
    "relatedNames": [
      "BDD",
      "TDD",
      "ATDD",
      "Microservices",
      "Smart&Small Monoliths",
      "Ubiquitous Language"
    ]
  },
  {
    "id": "devops",
    "symbol": "devops",
    "name": "DevOps",
    "category": "Techniques",
    "ring": "Adopt",
    "x": 237.27,
    "y": 214.23,
    "relatedNames": [
      "Automated Security Testing",
      "Statische Codeanalyse",
      "Microservices",
      "CICD",
      "Chaos Engineering",
      "Game Days",
      "GitLab",
      "DevOps",
      "Go",
      "SonarQube",
      "Docker",
      "Terraform",
      "Ansible",
      "Puppet",
      "DevSecOps",
      "Trivy",
      "DependencyTrack",
      "OpenTofu"
    ]
  },
  {
    "id": "gherkin",
    "symbol": "gherkin",
    "name": "Gherkin",
    "category": "Techniques",
    "ring": "Adopt",
    "x": 289.09,
    "y": 287.87,
    "relatedNames": [
      "BDD",
      "TDD",
      "ATDD",
      "Gherkin",
      "Ubiquitous Language",
      "DDD",
      "Cucumber",
      "SpecFlow"
    ]
  },
  {
    "id": "microfrontend",
    "symbol": "microfrontend",
    "name": "Microfrontend",
    "category": "Techniques",
    "ring": "Trial",
    "x": 161.92,
    "y": 227.11,
    "relatedNames": [
      "React",
      "Svelte",
      "Vue",
      "Storybook",
      "JavaScript",
      "StyleX"
    ]
  },
  {
    "id": "tailwindcss",
    "symbol": "tailwindcss",
    "name": "Tailwind CSS",
    "category": "Languages & Frameworks",
    "ring": "Trial",
    "x": 491.11,
    "y": 274.26,
    "relatedNames": [
      "React",
      "TypeScript",
      "Microfrontend",
      "Next.js",
      "JavaScript",
      "Storybook",
      "Sass",
      "Panda CSS",
      "StyleX",
      "sitespeed.io"
    ]
  },
  {
    "id": "opentofu",
    "symbol": "opentofu",
    "name": "OpenTofu",
    "category": "Languages & Frameworks",
    "ring": "Trial",
    "x": 490.87,
    "y": 204.16,
    "relatedNames": [
      "Terraform",
      "Serverless",
      "Kubernetes",
      "Puppet",
      "Ansible",
      "AWS",
      "Azure",
      "Google Cloud",
      "AWS ECS",
      "CICD",
      "OpenShift",
      "DevOps",
      "Docker",
      "Go",
      "Trivy",
      "OpenTofu"
    ]
  },
  {
    "id": "playwright",
    "symbol": "playwright",
    "name": "Playwright",
    "category": "Languages & Frameworks",
    "ring": "Assess",
    "x": 503.39,
    "y": 162.5,
    "relatedNames": [
      "TDD",
      "Unit-Test",
      "Integration und UI-Tests",
      "Jasmine",
      "Jest",
      "MSTest",
      "Browserstack",
      "Visual Regression Testing",
      "Selenium WebDriver",
      "ATDD",
      "Spock",
      "Protractor",
      "Cucumber",
      "Cypress",
      "Vitest",
      "Allure Report"
    ]
  },
  {
    "id": "vitest",
    "symbol": "vitest",
    "name": "Vitest",
    "category": "Languages & Frameworks",
    "ring": "Assess",
    "x": 461.89,
    "y": 130.48,
    "relatedNames": [
      "TDD",
      "Unit-Test",
      "Integration und UI-Tests",
      "Jasmine",
      "Jest",
      "MSTest",
      "Browserstack",
      "Visual Regression Testing",
      "Selenium WebDriver",
      "ATDD",
      "Spock",
      "Protractor",
      "Cucumber",
      "Karma",
      "Mocha",
      "Tape",
      "Enzyme",
      "Playwright"
    ]
  },
  {
    "id": "awsecs",
    "symbol": "awsecs",
    "name": "AWS ECS",
    "category": "Platforms",
    "ring": "Adopt",
    "x": 342.56,
    "y": 390.5,
    "relatedNames": [
      "AWS",
      "Azure",
      "AWS ECS",
      "CICD",
      "OpenShift",
      "DevOps",
      "AWS Lambda",
      "Docker",
      "Terraform",
      "Ansible",
      "AWS Cognito",
      "Serverless",
      "Smart&Small Monoliths",
      "Kubernetes",
      "AWS Amplify",
      "AWS CDK",
      "OpenTofu"
    ]
  },
  {
    "id": "azure",
    "symbol": "azure",
    "name": "Azure",
    "category": "Platforms",
    "ring": "Adopt",
    "x": 423.72,
    "y": 409.3,
    "relatedNames": [
      "AWS",
      "Azure",
      "CICD",
      "DevOps",
      "New Relic",
      "Docker",
      "Terraform",
      "API-Gateway",
      "Ansible",
      "Azure Active Directory",
      "Google Cloud",
      "Azure Cosmos DB",
      "Azure SQL Database",
      "OpenTofu"
    ]
  },
  {
    "id": "openshift",
    "symbol": "openshift",
    "name": "OpenShift",
    "category": "Platforms",
    "ring": "Adopt",
    "x": 382.62,
    "y": 446.3,
    "relatedNames": [
      "AWS",
      "Azure",
      "AWS ECS",
      "CICD",
      "OpenShift",
      "DevOps",
      "Docker",
      "Terraform",
      "Ansible",
      "Google Cloud",
      "OpenTofu"
    ]
  },
  {
    "id": "kubernetes",
    "symbol": "kubernetes",
    "name": "Kubernetes",
    "category": "Platforms",
    "ring": "Adopt",
    "x": 341.28,
    "y": 449.48,
    "relatedNames": [
      "Terraform",
      "Serverless",
      "Kubernetes",
      "Puppet",
      "Ansible",
      "AWS",
      "Azure",
      "Google Cloud",
      "AWS ECS",
      "CICD",
      "OpenShift",
      "DevOps",
      "Docker",
      "Go",
      "Trivy",
      "OpenTofu"
    ]
  },
  {
    "id": "googlecloud",
    "symbol": "googlecloud",
    "name": "Google Cloud",
    "category": "Platforms",
    "ring": "Assess",
    "x": 564.29,
    "y": 374.88,
    "relatedNames": [
      "AWS",
      "Azure",
      "Google Cloud",
      "OpenShift",
      "Docker",
      "Terraform",
      "Ansible",
      "Puppet",
      "Go",
      "OpenTofu"
    ]
  },
  {
    "id": "n8n",
    "symbol": "n8n",
    "name": "n8n",
    "category": "Platforms",
    "ring": "Assess",
    "x": 418.62,
    "y": 561.33,
    "relatedNames": [
      "ChatGPT",
      "Github Copilot",
      "Azure Cognitive Services",
      "Azure Search Service",
      "RAG",
      "Azure OpenAI Services",
      "Azure AI Foundry",
      "n8n",
      "Optimizely Opal",
      "OpenAI (Agent)",
      "MCP",
      "Vercel AI SDK"
    ]
  },
  {
    "id": "terraform",
    "symbol": "terraform",
    "name": "Terraform",
    "category": "Tools",
    "ring": "Adopt",
    "x": 190.95,
    "y": 362.33,
    "relatedNames": [
      "CICD",
      "Chaos Engineering",
      "DevOps",
      "Go",
      "Terraform",
      "Puppet",
      "Ansible",
      "AWS",
      "Azure",
      "Docker",
      "OpenTofu"
    ]
  },
  {
    "id": "storybook",
    "symbol": "storybook",
    "name": "Storybook",
    "category": "Tools",
    "ring": "Adopt",
    "x": 245.86,
    "y": 409.15,
    "relatedNames": [
      "Microfrontend",
      "Storybook",
      "Visual Regression Testing",
      "Selenium WebDriver",
      "Cypress",
      "Axure",
      "Abstract",
      "Bootstrap",
      "Sass",
      "StyleX"
    ]
  },
  {
    "id": "github-copilot",
    "symbol": "githubcopilot",
    "name": "GitHub Copilot",
    "category": "Tools",
    "ring": "Adopt",
    "x": 203.67,
    "y": 412.82,
    "relatedNames": [
      "ChatGPT",
      "Github Copilot",
      "Azure Cognitive Services",
      "Azure Search Service",
      "RAG",
      "Azure OpenAI Services",
      "Azure AI Foundry",
      "n8n",
      "Optimizely Opal",
      "OpenAI (Agent)",
      "MCP",
      "Vercel AI SDK"
    ]
  },
  {
    "id": "gitlab",
    "symbol": "gitlab",
    "name": "GitLab",
    "category": "Tools",
    "ring": "Adopt",
    "x": 252.74,
    "y": 450.32,
    "relatedNames": [
      "Teamcity",
      "DevOps",
      "CICD",
      "Merge-Request&Pull-Requests",
      "Trunk Based Development",
      "Short lived feature branches",
      "Semantic Versioning",
      "Azure Pipelines",
      "AWS CodePipeline",
      "AWS Amplify",
      "DevSecOps",
      "Trivy",
      "DependencyTrack"
    ]
  },
  {
    "id": "trivy",
    "symbol": "trivy",
    "name": "Trivy",
    "category": "Tools",
    "ring": "Trial",
    "x": 272.46,
    "y": 536.53,
    "relatedNames": [
      "OWASP ZAP API",
      "Automated Security Testing",
      "Arachni",
      "nmap",
      "WhiteSource",
      "Nikto2",
      "Retire.js",
      "OWASP Dependency-Check",
      "DevSecOps",
      "Trivy",
      "Azure Sentinel",
      "DependencyTrack"
    ]
  },
  {
    "id": "chatgpt",
    "symbol": "chatgpt",
    "name": "ChatGPT",
    "category": "Tools",
    "ring": "Assess",
    "x": 85.91,
    "y": 433.62,
    "relatedNames": [
      "ChatGPT",
      "Github Copilot",
      "Azure Cognitive Services",
      "Azure Search Service",
      "RAG",
      "Azure OpenAI Services",
      "Azure AI Foundry",
      "n8n",
      "Optimizely Opal",
      "OpenAI (Agent)",
      "MCP",
      "Vercel AI SDK"
    ]
  }
];
